services:
  - type: web
    name: reddit-sentiment-mcp
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python reddit_sentiment_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
